[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dave"
version = "0.1.2"
dependencies = [
  "tabulate",
  "pyyaml",
]

[project.scripts]
dave = "dave.cli:main"
